/*****BANNER********/
export const BANNER_REQUEST = "BANNER_REQUEST";
export const BANNER_SUCCESS = "BANNER_SUCCESS";
export const BANNER_FAIL = "BANNER_FAIL";
export const BANNER_START = "BANNER_START";

export const BANNER_DELETE_REQUEST = "BANNER_DELETE_REQUEST";
export const BANNER_DELETE_SUCCESS = "BANNER_DELETE_SUCCESS";
export const BANNER_DELETE_FAIL = "BANNER_DELETE_FAIL";

/*****  LIST   *****/
export const LIST_REQUEST = "LIST_REQUEST";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_FAIL = "LIST_FAIL";
export const LIST_START = "LIST_START";

export const LIST_GET_DETAILS_REQUEST = "LIST_GET_DETAILS_REQUEST";
export const LIST_GET_DETAILS_SUCCESS = "LIST_GET_DETAILS_SUCCESS";
export const LIST_GET_DETAILS_FAIL = "LIST_GET_DETAILS_FAIL";
/**********slider */
export const SLIDER_REQUEST = "SLIDER_REQUEST";
export const SLIDER_SUCCESS = "SLIDER_SUCCESS";
export const SLIDER_FAIL = "SLIDER_FAIL";
export const SLIDER_START = "SLIDER_START";

/**********Login */
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const UPDATE_USER_LOCATION = "UPDATE_USER_LOCATION";
export const AUTH_UPDATE_USER = "AUTH_UPDATE_USER";

/**********token */
export const SAVE_OAUTH_TOKEN = "SAVE_OAUTH_TOKEN";
export const DELETE_OAUTH_TOKEN = "DELETE_OAUTH_TOKEN";

/*****************register */
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_START = "REGISTER_USER_START";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_START = "ADD_USER_START";

/*****************Contact */
export const CONTACT_USER_REQUEST = "CONTACT_USER_REQUEST";
export const CONTACT_USER_SUCCESS = "CONTACT_USER_SUCCESS";
export const CONTACT_USER_FAIL = "CONTACT_USER_FAIL";
export const CONTACT_USER_START = "CONTACT_USER_START";

export const CONTACT_ADD_REQUEST = "CONTACT_ADD_REQUEST";
export const CONTACT_ADD_SUCCESS = "CONTACT_ADD_SUCCESS";
export const CONTACT_ADD_FAIL = "CONTACT_ADD_FAIL";
export const CONTACT_ADD_START = "CONTACT_ADD_START";

/*****************collectionType */
export const COLLECTION_TYPE_REQUEST = "COLLECTION_TYPE_REQUEST";
export const COLLECTION_TYPE_SUCCESS = "COLLECTION_TYPE_SUCCESS";
export const COLLECTION_TYPE_FAIL = "COLLECTION_TYPE_FAIL";
export const COLLECTION_TYPE_START = "COLLECTION_TYPE_START";

/*************cart actions */
export const GET_IN_CART_REQUEST = "GET_IN_CART_REQUEST";
export const GET_IN_CART_SUCCESS = "GET_IN_CART_SUCCESS";
export const GET_IN_CART_FAILED = "GET_IN_CART_FAILED";
