export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

export const GET_TO_CART_REQUEST = "GET_TO_CART_REQUEST";
export const GET_TO_CART_SUCCESS = "GET_TO_CART_SUCCESS";
export const GET_TO_CART_FAILED = "GET_TO_CART_FAILED";

export const ADJUST_ITEM_QTY = "ADJUST_ITEM_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";

export const FETCH_DATA_CART_REQUEST = "FETCH_DATA_CART_REQUEST";
export const FETCH_DATA_CART_SUCCESS = "FETCH_DATA_CART_SUCCESS";
export const FETCH_DATA_CART_FAIL = "FETCH_DATA_CART_FAIL";

export const ADD_IN_CART_REQUEST = "ADD_IN_CART_REQUEST";
export const ADD_IN_CART_SUCCESS = "ADD_IN_CART_SUCCESS";
export const ADD_IN_CART_FAILED = "ADD_IN_CART_FAILED";

export const GET_IN_CART_REQUEST_BY_ID = "GET_IN_CART_REQUEST_BY_ID";
export const GET_IN_CART_SUCCESS_BY_ID = "GET_IN_CART_SUCCESS_BY_ID";
export const GET_IN_CART_FAILED_BY_ID = "GET_IN_CART_FAILED_BY_ID";

export const UPDATE_IN_CART_REQUEST = "UPDATE_IN_CART_REQUEST";
export const UPDATE_IN_CART_SUCCESS = "UPDATE_IN_CART_SUCCESS";
export const UPDATE_IN_CART_FAILED = "UPDATE_IN_CART_FAILED";

export const DELETE_IN_CART_REQUEST = "DELETE_IN_CART_REQUEST";
export const DELETE_IN_CART_SUCCESS = "DELETE_IN_CART_SUCCESS";
export const DELETE_IN_CART_FAILED = "DELETE_IN_CART_FAILED";

export const ORDER_FORM_REQUEST = "ORDER_FORM_REQUEST";
export const ORDER_FORM_SUCCESS = "ORDER_FORM_SUCCESS";
export const ORDER_FORM_FAILED = "ORDER_FORM_FAILED";

export const ORDER_GET_REQUEST = "ORDER_GET_REQUEST";
export const ORDER_GET_SUCCESS = "ORDER_GET_SUCCESS";
export const ORDER_GET_FAILED = "ORDER_GET_FAILED";

export const PAYMENT_BILL_REQUEST = "PAYMENT_BILL_REQUEST";
export const PAYMENT_BILL_SUCCESS = "PAYMENT_BILL_SUCCESS";
export const PAYMENT_BILL_FAILED = "PAYMENT_BILL_FAILED";

export const RESET_STATUS = "RESET_STATUS";
